public with sharing class IntermediateDate1 
{
    // Change the method below to return the number of hours between the two dates.
    //
    // - The dates are supplied as strings with the following format : dd/mm/yy HH:MM:ss
    //
    // - Either date1 or date2 may be the earliest date, but the result should always be a
    //    positive number of hours. 
    //
    // - Fractional hours should be discarded, so a result that would be 129.9 hours would 
    //   give a return value of 129.
    //
    // - If either date is null, the result should be zero.
    // 
    // - Assume both date/times are specified in your timezone
    //
    // - Assume if date is not null it is correctly formatted - no need to check for empty or 
    //   unparseable strings
    //
    public static Integer HoursBetweenDateTimes(String dateStr1, String dateStr2) 
    {
    }
}
